name: MLflow Training
on:
  push:
    branches: [ main ]
jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.7'
    - name: Install dependencies
      run: |
        pip install mlflow==2.19.0 pandas scikit-learn
    - name: Run MLflow Project
      run: |
        cd MLProject
        mlflow run .
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: mlflow-artifacts
        path: mlruns/
